Thank you for the author and contribution from @Peter in this [post](https://stackoverflow.com/questions/32791911/fast-calculation-of-pareto-front-in-python).

In [1]:
import numpy as np

In [2]:
def is_pareto_efficient(costs, return_mask = True):
    """
    Find the pareto-efficient points
    :param costs: An (n_points, n_costs) array
    :param return_mask: True to return a mask
    :return: An array of indices of pareto-efficient points.
        If return_mask is True, this will be an (n_points, ) boolean array
        Otherwise it will be a (n_efficient_points, ) integer array of indices.
    """
    is_efficient = np.arange(costs.shape[0])
    n_points = costs.shape[0]
    next_point_index = 0  # Next index in the is_efficient array to search for
    while next_point_index<len(costs):
        nondominated_point_mask = np.any(costs>costs[next_point_index], axis=1)
        nondominated_point_mask[next_point_index] = True
        is_efficient = is_efficient[nondominated_point_mask]  # Remove dominated points
        costs = costs[nondominated_point_mask]
        next_point_index = np.sum(nondominated_point_mask[:next_point_index])+1
    if return_mask:
        is_efficient_mask = np.zeros(n_points, dtype = bool)
        is_efficient_mask[is_efficient] = True
        return is_efficient_mask
    else:
        return is_efficient

In [3]:
sample = np.array([[1.01, 0.0, 2.01], [2.01,0.0, 3.01], [5.01, 0.0, 6.01], [2.01, 0.0, 1.01], [4.01, 0.0, 1.01]])
sample

array([[1.01, 0.  , 2.01],
       [2.01, 0.  , 3.01],
       [5.01, 0.  , 6.01],
       [2.01, 0.  , 1.01],
       [4.01, 0.  , 1.01]])

In [5]:
pf_indice = is_pareto_efficient(sample)
pf_indice

array([False, False,  True, False, False])

In [6]:
pf = is_pareto_efficient(sample, return_mask=False)
pf

array([2])

In [7]:
sample[pf]

array([[5.01, 0.  , 6.01]])